'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CalendarDays, Eye, MousePointerClick, RefreshCw, Wallet } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

type Row = Record<string, unknown>
type Aggregate = { name: string; spend: number; impressions: number; clicks: number; conversions: number; reach: number; ctr: number; cpc: number; cpm: number; image?: string }
const n = (v: unknown) => Number(v || 0)
const text = (v: unknown) => String(v || '-').trim()
const money = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 2 })
const integer = (v: number) => v.toLocaleString('pt-BR', { maximumFractionDigits: 0 })

function aggregate(rows: Row[], key: string): Aggregate[] {
  const map = new Map<string, Aggregate>()
  for (const row of rows) {
    const name = text(row[key])
    const current = map.get(name) || { name, spend: 0, impressions: 0, clicks: 0, conversions: 0, reach: 0, ctr: 0, cpc: 0, cpm: 0, image: text(row.image_url) !== '-' ? text(row.image_url) : undefined }
    current.spend += n(row.spend); current.impressions += n(row.impressions); current.clicks += n(row.clicks); current.conversions += n(row.conversions || row.purchases || row.leads); current.reach += n(row.reach)
    current.ctr = current.impressions ? current.clicks / current.impressions * 100 : 0; current.cpc = current.clicks ? current.spend / current.clicks : 0; current.cpm = current.impressions ? current.spend / current.impressions * 1000 : 0
    map.set(name, current)
  }
  return [...map.values()].sort((a, b) => b.spend - a.spend)
}

export default function PerformancePage() {
  const today = new Date(); const prior = new Date(today); prior.setDate(today.getDate() - 29)
  const iso = (d: Date) => d.toISOString().slice(0, 10)
  const [source, setSource] = useState('meta'); const [from, setFrom] = useState(iso(prior)); const [to, setTo] = useState(iso(today)); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const r = await fetch(`/api/windsor/performance?source=${source}&from=${from}&to=${to}`, { cache: 'no-store' }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Não foi possível carregar os dados.'); setRows(Array.isArray(d) ? d : d.data || d.rows || []) } catch (e) { setRows([]); setError(e instanceof Error ? e.message : 'Não foi possível carregar os dados.') } finally { setLoading(false) } }, [source, from, to])
  useEffect(() => { void load() }, [load])
  const totals = useMemo(() => rows.reduce<{ spend: number; impressions: number; reach: number; clicks: number; conversions: number }>((a, r) => ({ spend: a.spend + n(r.spend), impressions: a.impressions + n(r.impressions), reach: a.reach + n(r.reach), clicks: a.clicks + n(r.clicks), conversions: a.conversions + n(r.conversions || r.purchases || r.leads) }), { spend: 0, impressions: 0, reach: 0, clicks: 0, conversions: 0 }), [rows])
  const ctr = totals.impressions ? totals.clicks / totals.impressions * 100 : 0; const cpc = totals.clicks ? totals.spend / totals.clicks : 0; const cpm = totals.impressions ? totals.spend / totals.impressions * 1000 : 0
  const campaigns = useMemo(() => aggregate(rows, 'campaign'), [rows]); const creatives = useMemo(() => aggregate(rows, 'ad_name'), [rows]); const daily = useMemo(() => aggregate(rows.map(r => ({ ...r, campaign: r.date })), 'campaign').reverse(), [rows])
  return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Performance de anúncios</h1><p className="mt-1 text-sm text-muted-foreground">Visão consolidada de campanhas e criativos do Windsor.ai</p></div><div className="flex flex-wrap items-center gap-2"><Button variant={source === 'meta' ? 'default' : 'outline'} onClick={() => setSource('meta')}>Meta Ads</Button><Button variant={source === 'google' ? 'default' : 'outline'} onClick={() => setSource('google')}>Google Ads</Button><Button variant="outline" onClick={() => void load}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button></div></header><Card className="flex flex-wrap items-end gap-3 p-4"><CalendarDays className="mb-2 h-4 w-4 text-muted-foreground" /><label className="text-xs text-muted-foreground">De<Input type="date" value={from} onChange={e => setFrom(e.target.value)} className="mt-1 w-40" /></label><label className="text-xs text-muted-foreground">Até<Input type="date" value={to} onChange={e => setTo(e.target.value)} className="mt-1 w-40" /></label><Button onClick={() => void load}>Aplicar período</Button></Card>{error && <Card className="p-4 text-sm text-amber-500">{error}</Card>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Investimento" value={money(totals.spend)} icon={Wallet} /><Metric label="Impressões" value={integer(totals.impressions)} icon={Eye} /><Metric label="Cliques" value={integer(totals.clicks)} icon={MousePointerClick} /><Metric label="CTR" value={`${ctr.toFixed(2)}%`} icon={MousePointerClick} /></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Alcance" value={integer(totals.reach)} /><Metric label="CPC médio" value={money(cpc)} /><Metric label="CPM médio" value={money(cpm)} /></div><Card className="p-5"><h2 className="mb-4 text-sm font-semibold">Evolução diária</h2>{loading ? <div className="h-64 animate-pulse rounded bg-muted" /> : <ResponsiveContainer width="100%" height={260}><AreaChart data={daily}><defs><linearGradient id="spendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="hsl(var(--primary))" stopOpacity={0.35} /><stop offset="95%" stopColor="hsl(var(--primary))" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" opacity={0.15} /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={(v) => money(Number(v))} /><Area type="monotone" dataKey="spend" name="Investimento" stroke="hsl(var(--primary))" fill="url(#spendFill)" /></AreaChart></ResponsiveContainer>}</Card><div className="grid gap-4 lg:grid-cols-2"><Ranking title="Principais campanhas" rows={campaigns} /><Ranking title="Principais criativos" rows={creatives} showImage /></div></div>
}
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon?: typeof Wallet }) { return <Card className="p-4"><div className="flex items-center gap-2 text-sm text-muted-foreground">{Icon && <Icon className="h-4 w-4" />}{label}</div><p className="mt-2 text-2xl font-semibold">{value}</p></Card> }
function Ranking({ title, rows, showImage }: { title: string; rows: Aggregate[]; showImage?: boolean }) { return <Card className="overflow-hidden"><div className="border-b p-5"><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">Ordenados por investimento</p></div><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="p-3">{showImage ? 'Criativo' : 'Campanha'}</th><th className="p-3 text-right">Investimento</th><th className="p-3 text-right">Cliques</th><th className="p-3 text-right">CTR</th><th className="p-3 text-right">CPC</th></tr></thead><tbody>{rows.slice(0, 10).map(r => <tr key={r.name} className="border-b last:border-0"><td className="max-w-56 p-3"><div className="flex items-center gap-2">{showImage && r.image && <img src={r.image} alt="" className="h-8 w-8 rounded object-cover" />}{r.name}</div></td><td className="p-3 text-right">{money(r.spend)}</td><td className="p-3 text-right">{integer(r.clicks)}</td><td className="p-3 text-right">{r.ctr.toFixed(2)}%</td><td className="p-3 text-right">{money(r.cpc)}</td></tr>)}</tbody></table>{rows.length === 0 && <p className="p-5 text-sm text-muted-foreground">Nenhum dado no período selecionado.</p>}</div></Card>}
