'use client'
import { useEffect, useMemo, useState } from 'react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { BarChart3, RefreshCw } from 'lucide-react'
type Row = Record<string, unknown>
export default function PerformancePage() { const [source, setSource] = useState('meta'); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  async function load() { setLoading(true); setError(''); const r = await fetch(`/api/windsor/performance?source=${source}`, { cache: 'no-store' }); const d = await r.json(); setLoading(false); if (!r.ok) return setError(d.error || 'Não foi possível carregar'); setRows(Array.isArray(d) ? d : d.data || d.rows || []) }
  useEffect(() => { load() }, [source]); const totals = useMemo(() => rows.reduce<{ spend: number; impressions: number; clicks: number }>((a, r) => ({ spend: a.spend + Number(r.spend || 0), impressions: a.impressions + Number(r.impressions || 0), clicks: a.clicks + Number(r.clicks || 0) }), { spend: 0, impressions: 0, clicks: 0 }), [rows])
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Performance de anúncios</h1><p className="mt-1 text-sm text-muted-foreground">Resultados importados do Windsor.ai</p></div><div className="flex gap-2"><Button variant={source === 'meta' ? 'default' : 'outline'} onClick={() => setSource('meta')}>Meta Ads</Button><Button variant={source === 'google' ? 'default' : 'outline'} onClick={() => setSource('google')}>Google Ads</Button><Button variant="outline" onClick={load}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button></div></div>{error && <Card className="p-5 text-sm text-amber-500">{error}</Card>}<div className="grid gap-4 sm:grid-cols-3"><Metric label="Investimento" value={totals.spend.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })} /><Metric label="Impressões" value={totals.impressions.toLocaleString('pt-BR')} /><Metric label="Cliques" value={totals.clicks.toLocaleString('pt-BR')} /></div><Card className="overflow-auto p-5">{loading ? <p>Carregando...</p> : rows.length === 0 ? <div className="flex items-center gap-2 text-sm text-muted-foreground"><BarChart3 className="h-4 w-4" />Nenhum dado retornado.</div> : <table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Data</th><th className="p-2">Campanha</th><th className="p-2">Investimento</th><th className="p-2">Impressões</th><th className="p-2">Cliques</th><th className="p-2">CTR</th></tr></thead><tbody>{rows.map((r, i) => <tr key={i} className="border-b"><td className="p-2">{String(r.date || '-')}</td><td className="p-2">{String(r.campaign || r.campaign_name || '-')}</td><td className="p-2">{String(r.spend || 0)}</td><td className="p-2">{String(r.impressions || 0)}</td><td className="p-2">{String(r.clicks || 0)}</td><td className="p-2">{String(r.ctr || 0)}</td></tr>)}</tbody></table>}</Card></div> }
function Metric({ label, value }: { label: string; value: string }) { return <Card className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card> }
