import { NextResponse } from 'next/server'
import { getCurrentAccount, toErrorResponse } from '@/lib/auth/account'
import { decrypt } from '@/lib/whatsapp/encryption'

function rowsFrom(value: unknown): unknown[] {
  if (Array.isArray(value)) return value
  if (!value || typeof value !== 'object') return []
  const object = value as Record<string, unknown>
  for (const key of ['data', 'rows', 'results', 'result', 'records']) {
    const rows = rowsFrom(object[key])
    if (rows.length) return rows
  }
  return []
}

export async function GET(request: Request) {
  try {
    const { supabase, accountId } = await getCurrentAccount()
    const params = new URL(request.url).searchParams
    const source = params.get('source') === 'google' ? 'google_ads_url' : 'meta_ads_url'
    const { data, error } = await supabase.from('windsor_configs').select('meta_ads_url, google_ads_url').eq('account_id', accountId).maybeSingle()
    if (error) throw error
    if (!data?.[source]) return NextResponse.json({ error: 'Configure o link do Windsor para esta fonte em Configurações.' }, { status: 404 })
    // The saved Windsor URL already contains its date preset and fields.
    // Do not replace date_preset with date_from/date_to: connector URLs
    // generated by Windsor may reject that combination and return no rows.
    const upstream = await fetch(decrypt(data[source]), { cache: 'no-store' })
    const json = await upstream.json()
    return NextResponse.json(rowsFrom(json), { status: upstream.ok ? 200 : upstream.status })
  } catch (err) { return toErrorResponse(err) }
}
